"""Updated main entrypoint for modular Urdu TTS."""
if __name__ == "__main__":
    from src.pipeline import UrduSpeechPipeline
    from src.config import TTSConfig, TranscriberConfig
    
    # Demo usage
    INPUT_AUDIO = "sample_input.wav"
    OUTPUT_AUDIO = "output.wav"
    
    pipeline = UrduSpeechPipeline(
        tts_config=TTSConfig(num_steps=30),
        transcriber_config=TranscriberConfig(model_size="small")
    )
    
    try:
        result = pipeline.process_audio(
            INPUT_AUDIO, 
            OUTPUT_AUDIO,
            modify_text=lambda t: t + " - Generated by modular pipeline."
        )
        print(f"✅ Success! Text: {result}")
        print("💡 Run Streamlit app: streamlit run app.py")
    except Exception as e:
        print(f"❌ Error: {e}")
        print("📝 Update paths and install: pip install -r requirements.txt")

